# Dockerfile for Backend (Nest.js)
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose the port that the NestJS app runs on
EXPOSE 3001

# Start the NestJS application
CMD ["npm", "run", "start:prod"]
